name: linux-build-and-unit-test

on:
  pull_request:

jobs:
  linux-build-and-unit-test:
    runs-on: 2xlarge
    container:
      image: prestocpp/prestocpp-avx-centos:root-20230613
    env:
      MAVEN_OPTS: "-Xmx4G -XX:+ExitOnOutOfMemoryError"
      MAVEN_INSTALL_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError"
      MAVEN_FAST_INSTALL: "-B -V --quiet -T C1 -DskipTests -Dair.check.skip-all -Dmaven.javadoc.skip=true"
      MAVEN_TEST: "-B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true --fail-at-end"
    steps:
      - uses: actions/checkout@v4.1.1
      - name: "Update velox"
        run: |
          cd presto-native-execution
          make velox-submodule
      - name: "Install JWT adapter dependency"
        run: |
          mkdir -p ${HOME}/adapter-deps/install
          source /opt/rh/gcc-toolset-9/enable
          set -xu
          cd presto-native-execution
          DEPENDENCY_DIR=${HOME}/adapter-deps PROMPT_ALWAYS_RESPOND=n ./scripts/setup-adapters.sh jwt
      - name: "Calculate merge-base date for CCache"
        run: git show -s --format=%cd --date="format:%Y%m%d" $(git merge-base origin/master HEAD) | tee merge-base-date
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.10
        with:
          key: native-exe-linux-ccache-${{ runner.os }}-${{ hashFiles('merge-base-date') }}
      - name: Build
        run: |
          mkdir -p .ccache
          export CCACHE_DIR=$(realpath .ccache)
          ccache -sz -M 8Gi
          source /opt/rh/gcc-toolset-9/enable
          cd presto-native-execution
          cmake \
            -B _build/debug \
            -GNinja \
            -DTREAT_WARNINGS_AS_ERRORS=1 \
            -DENABLE_ALL_WARNINGS=1 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DPRESTO_ENABLE_PARQUET=ON \
            -DPRESTO_ENABLE_REMOTE_FUNCTIONS=ON \
            -DPRESTO_ENABLE_JWT=ON \
            -DCMAKE_PREFIX_PATH=/usr/local \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DMAX_LINK_JOBS=2
          ninja -C _build/debug -j 8
      - name: 'Run Unit Tests'
        run: |
          cd presto-native-execution/_build/debug
          ctest -j 10 -VV --output-on-failure --exclude-regex velox.*
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: presto-native-execution
          path: |
            _build/debug/presto_cpp/main/presto_server
            _build/debug/velox/velox/functions/remote/server/velox_functions_remote_server_main
  
  linux-presto-e2e-tests:
    runs-on: 2xlarge
    container:
      image: prestocpp/prestocpp-avx-centos:root-20230613
    env:
      MAVEN_OPTS: "-Xmx4G -XX:+ExitOnOutOfMemoryError"
      MAVEN_INSTALL_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError"
      MAVEN_FAST_INSTALL: "-B -V --quiet -T C1 -DskipTests -Dair.check.skip-all -Dmaven.javadoc.skip=true"
      MAVEN_TEST: "-B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true --fail-at-end"
    steps:
      - uses: actions/checkout@v4.1.1
      - name: 'Download artifacts'
        uses: actions/download-artifact@v2
        with:
          name: presto-native-execution
      - run: ls -R